version: '3'
networks:
  papernet:
    driver: overlay
    driver_opts:
      encrypted: "true"

services:

  devproxy:
    build: devproxy/
    networks:
      - papernet
    ports:
      - "2222:22"
