# ╔════════════════════════════════════════════════════════════════════════════╗
# ║                                                                            ║
# ║              _ \                                           |               ║
# ║             |   | _` | __ \   _ \  __|\ \  \   / _ \   __| |  /            ║
# ║             ___/ (   | |   |  __/ |    \ \  \ / (   | |      <             ║
# ║            _|   \__,_| .__/ \___|_|     \_/\_/ \___/ _|   _|\_\            ║
# ║                       _|                                                   ║
# ║                                                                            ║
# ║           * github.com/paperwork * twitter.com/paperworkcloud *            ║
# ║                                                                            ║
# ╚════════════════════════════════════════════════════════════════════════════╝
version: '3.7'

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Networks                                                                   ║
# ║                                                                            ║
# ║ Please make sure to create this network before launching this stack        ║
# ║ file, otherwise composer won't be able to deploy.                          ║
# ╚════════════════════════════════════════════════════════════════════════════╝
networks:
  papernet:
    driver: overlay
    driver_opts:
      encrypted: "true"

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Services                                                                   ║
# ╚════════════════════════════════════════════════════════════════════════════╝
services:

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Database                                                                   ║
# ╚════════════════════════════════════════════════════════════════════════════╝
  db:
    image: mongo:latest
    command: --wiredTigerCacheSizeGB 1.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - type: bind
        source: ./volumes/mongodb
        target: /data/db
    networks:
      - papernet
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 360s

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ File storage                                                               ║
# ╚════════════════════════════════════════════════════════════════════════════╝
  storage:
    image: minio:latest
    command: server /data
    environment:
      MINIO_ACCESS_KEY: root
      MINIO_SECRET_KEY: roooooot
    volumes:
      - type: bind
        source: ./volumes/minio
        target: /data/db
    networks:
      - papernet
    ports:
      - target: 9000
        published: 8080
        protocol: tcp
        mode: host
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 360s

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Gatekeeper Service                                                         ║
# ╚════════════════════════════════════════════════════════════════════════════╝
  service_gatekeeper:
    image: paperwork/service-gatekeeper:latest
    environment:
      CONFIG_JSON: '{"port":8080,"jwt_secret":"ru4XngBQ/uXZX4o/dTjy3KieL7OHkqeKwGH9KhClVnfpEaRcpw+rNvvSiC66dyiY","services":[{"name":"users","target":"http://service_users:8080","endpoints":["/users","/registration","/login"]},{"name":"notes","target":"http://service_notes:8080","endpoints":["/notes"]},{"name":"storages","target":"http://service_storages:8080","endpoints":["/attachments"]}]}'
    networks:
      - papernet
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 60s

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Configs Service                                                            ║
# ╚════════════════════════════════════════════════════════════════════════════╝
  service_configs:
    image: paperwork/service-configs:latest
    environment:
      PORT: 8080
      MONGODB_URL: mongodb://db:27017/configs
      INTERNAL_RESOURCE_CONFIGS: http://service_configs:8080/internal/configs
      INTERNAL_RESOURCE_USERS: http://service_users:8080/internal/users
      INTERNAL_RESOURCE_NOTES: http://service_notes:8080/internal/notes
      INTERNAL_RESOURCE_ATTACHMENTS: http://service_storages:8080/internal/attachments
    networks:
      - papernet
    depends_on:
      - db
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Users Service                                                              ║
# ╚════════════════════════════════════════════════════════════════════════════╝
  service_users:
    image: paperwork/service-users:latest
    environment:
      PORT: 8080
      JWT_SECRET: "ru4XngBQ/uXZX4o/dTjy3KieL7OHkqeKwGH9KhClVnfpEaRcpw+rNvvSiC66dyiY"
      MONGODB_URL: mongodb://db:27017/users
      INTERNAL_RESOURCE_CONFIGS: http://service_configs:8080/internal/configs
      INTERNAL_RESOURCE_USERS: http://service_users:8080/internal/users
      INTERNAL_RESOURCE_NOTES: http://service_notes:8080/internal/notes
      INTERNAL_RESOURCE_ATTACHMENTS: http://service_storages:8080/internal/attachments
    networks:
      - papernet
    depends_on:
      - db
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Notes Service                                                              ║
# ╚════════════════════════════════════════════════════════════════════════════╝
  service_notes:
    image: paperwork/service-notes:latest
    environment:
      PORT: 8080
      MONGODB_URL: mongodb://db:27017/notes
      INTERNAL_RESOURCE_CONFIGS: http://service_configs:8080/internal/configs
      INTERNAL_RESOURCE_USERS: http://service_users:8080/internal/users
      INTERNAL_RESOURCE_NOTES: http://service_notes:8080/internal/notes
      INTERNAL_RESOURCE_ATTACHMENTS: http://service_storages:8080/internal/attachments
    networks:
      - papernet
    depends_on:
      - db
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Storages Service                                                           ║
# ╚════════════════════════════════════════════════════════════════════════════╝
  service_storages:
    image: paperwork/service-storages:latest
    environment:
      PORT: 8080
      MONGODB_URL: mongodb://db:27017/storages
      STORAGE_URL: http://storage:8080
      AWS_ACCESS_KEY_ID: root
      AWS_SECRET_ACCESS_KEY: roooooot
      INTERNAL_RESOURCE_CONFIGS: http://service_configs:8080/internal/configs
      INTERNAL_RESOURCE_USERS: http://service_users:8080/internal/users
      INTERNAL_RESOURCE_NOTES: http://service_notes:8080/internal/notes
      INTERNAL_RESOURCE_ATTACHMENTS: http://service_storages:8080/internal/attachments
    networks:
      - papernet
    depends_on:
      - db
      - storage
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ Web UI                                                                     ║
# ╚════════════════════════════════════════════════════════════════════════════╝
  web:
    image: paperwork/web:latest
    environment:
      PORT: 8080
      PAPERWORK_API_GATEWAY_PROTOCOL: http
      PAPERWORK_API_GATEWAY_HOST_PORT: service_gatekeeper:8080
    networks:
      - papernet
    depends_on:
      - service_gatekeeper
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
